### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chanchalpatil**
Aligned the three images in a single row.

### CODE REVIEW

**Comment by Himanshuranjan30** [comment]
You want it merged now or after the hacktoberfest starts?

**Comment by chanchalpatil** [comment]
I'd be super thankful if you could merge it after Hacktober starts :)

**Comment by Himanshuranjan30** [comment]
Sure @chanchalpatil

**Comment by chanchalpatil** [comment]
@Himanshuranjan30 Could you please label my PR as "hacktoberfest-accepted" ?

**Comment by Himanshuranjan30** [comment]
not needed @chanchalpatil

**Comment by chanchalpatil** [comment]
alright @Himanshuranjan30

**Pull request merged**
